# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Apparelslt.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5.QtWidgets import  QFileDialog
from PyQt5 import QtCore, QtGui, QtWidgets

from com_ineuron_firensmoke.com_ineuron_utils.utils import decodeImage
from com_ineuron_firensmoke.predictor_yolo_detector.detector_test import Detector

class ClientApp:
    def __init__(self):
        self.filename = "inputImage.jpg"
        #modelPath = 'research/ssd_mobilenet_v1_coco_2017_11_17'
        self.objectDetection = Detector(self.filename)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Photo = QtWidgets.QLabel(self.centralwidget)
        self.Photo.setGeometry(QtCore.QRect(10, 60, 601, 391))
        self.Photo.setText("")
        self.Photo.setPixmap(QtGui.QPixmap("../../Internship/Apparel_Detection/com_ineuron_firensmoke/predictor_yolo_detector/inference/images/inputImage.jpg"))
        self.Photo.setScaledContents(True)
        self.Photo.setObjectName("Photo")
        self.Cat = QtWidgets.QPushButton(self.centralwidget)
        self.Cat.setGeometry(QtCore.QRect(70, 490, 181, 51))
        self.Cat.setObjectName("Cat")
        self.Dog = QtWidgets.QPushButton(self.centralwidget)
        self.Dog.setGeometry(QtCore.QRect(390, 490, 161, 51))
        self.Dog.setObjectName("Dog")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(180, 10, 381, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(650, 120, 51, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(650, 170, 47, 13))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(650, 210, 51, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(650, 260, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(650, 320, 47, 13))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.Cat.clicked.connect(self.show_upload)
        self.Dog.clicked.connect(self.show_predict)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Cat.setText(_translate("MainWindow", "Upload"))
        self.Cat.setShortcut(_translate("MainWindow", "Ctrl+U"))
        self.Dog.setText(_translate("MainWindow", "Predict"))
        self.Dog.setShortcut(_translate("MainWindow", "Ctrl+P"))
        self.label.setText(_translate("MainWindow", "INeuron Apparels Detection"))
        self.label_2.setText(_translate("MainWindow", "Hat"))
        self.label_3.setText(_translate("MainWindow", "Vest"))
        self.label_4.setText(_translate("MainWindow", "Goggles"))
        self.label_5.setText(_translate("MainWindow", "Glove"))
        self.label_6.setText(_translate("MainWindow", "Shoe"))

    def show_upload(self):
        fname = QFileDialog.getOpenFileName(self, 'Open file','c:\\', "Images(*.jpg, *.jpeg)")
        #
        self.Photo.setPixmap(QtGui.QPixmap(fname))
        #save the file getSaveFileName()
        # self.Photo.setPixmap(QtGui.QPixmap("com_ineuron_firensmoke/predictor_yolo_detector/inference/images/inputImage.JPG"))

    def show_predict(self):
        result = clApp.objectDetection.detect_action()
        noclass = clApp.objectDetection.noclassdesc
        print(" ******no of classes detected"+noclass)
        print("no of classes detected -->" + str(noclass))
        self.label_2.setText("Hat =" + noclass)
        output = result[0]['image']
        self.Photo.setPixmap(QtGui.QPixmap("output.JPG"))

clApp = ClientApp()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
