version: '3'

services:
  web:
    build: .
    image: chalumuri/apparels:1.0
    environment:
      - FLASK_ENV=development
    ports:
      - 5000:5000
    links:
      - db

  db:
    image: mongo:3.0.2
    ports:
      - 27017:27017



